/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.gersua.softserve.challege;

import java.util.stream.Collectors;

public class Main {

    public String uniqueCharatersString(String str) {
        if (str == null) {
            return "";
        }

        return str.chars()
                .distinct()
                .mapToObj(c -> String.valueOf((char) c))
                .collect(Collectors.joining());
    }

    public static void main(String[] args) {
        var main = new Main();
        System.out.println(main.uniqueCharatersString("AABBCCD112233"));
    }
}
